# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../include/mainwindow.ui'
#
# Created: Fri Sep  1 18:18:04 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1920, 1080)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(630, 690, 601, 261))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.btnStartExperiment = QtGui.QPushButton(self.groupBox_4)
        self.btnStartExperiment.setGeometry(QtCore.QRect(10, 130, 571, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartExperiment.setFont(font)
        self.btnStartExperiment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStartExperiment.setObjectName(_fromUtf8("btnStartExperiment"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(660, 40, 491, 121))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(340, 200, 1241, 551))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        self.textEdit.setFont(font)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.lcdNumberTotal = QtGui.QLCDNumber(self.tab)
        self.lcdNumberTotal.setGeometry(QtCore.QRect(340, 40, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberTotal.setFont(font)
        self.lcdNumberTotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumberTotal.setAutoFillBackground(False)
        self.lcdNumberTotal.setProperty("intValue", 0)
        self.lcdNumberTotal.setObjectName(_fromUtf8("lcdNumberTotal"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(340, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(1450, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lcdNumberTotalRobot = QtGui.QLCDNumber(self.tab)
        self.lcdNumberTotalRobot.setGeometry(QtCore.QRect(1450, 50, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberTotalRobot.setFont(font)
        self.lcdNumberTotalRobot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumberTotalRobot.setAutoFillBackground(False)
        self.lcdNumberTotalRobot.setProperty("intValue", 0)
        self.lcdNumberTotalRobot.setObjectName(_fromUtf8("lcdNumberTotalRobot"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 10, 161, 951))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_0 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_0.setObjectName(_fromUtf8("pushButton_0"))
        self.verticalLayout_2.addWidget(self.pushButton_0)
        self.pushButton_1 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.verticalLayout_2.addWidget(self.pushButton_1)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.widget1 = QtGui.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(1710, 10, 161, 951))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_0r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0r.setFont(font)
        self.pushButton_0r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_0r.setObjectName(_fromUtf8("pushButton_0r"))
        self.verticalLayout_3.addWidget(self.pushButton_0r)
        self.pushButton_1r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1r.setFont(font)
        self.pushButton_1r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1r.setObjectName(_fromUtf8("pushButton_1r"))
        self.verticalLayout_3.addWidget(self.pushButton_1r)
        self.pushButton_2r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2r.setFont(font)
        self.pushButton_2r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2r.setObjectName(_fromUtf8("pushButton_2r"))
        self.verticalLayout_3.addWidget(self.pushButton_2r)
        self.pushButton_3r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3r.setFont(font)
        self.pushButton_3r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3r.setObjectName(_fromUtf8("pushButton_3r"))
        self.verticalLayout_3.addWidget(self.pushButton_3r)
        self.pushButton_4r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4r.setFont(font)
        self.pushButton_4r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4r.setObjectName(_fromUtf8("pushButton_4r"))
        self.verticalLayout_3.addWidget(self.pushButton_4r)
        self.pushButton_5r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5r.setFont(font)
        self.pushButton_5r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5r.setObjectName(_fromUtf8("pushButton_5r"))
        self.verticalLayout_3.addWidget(self.pushButton_5r)
        self.pushButton_6r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6r.setFont(font)
        self.pushButton_6r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6r.setObjectName(_fromUtf8("pushButton_6r"))
        self.verticalLayout_3.addWidget(self.pushButton_6r)
        self.pushButton_7r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7r.setFont(font)
        self.pushButton_7r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7r.setObjectName(_fromUtf8("pushButton_7r"))
        self.verticalLayout_3.addWidget(self.pushButton_7r)
        self.pushButton_8r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8r.setFont(font)
        self.pushButton_8r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8r.setObjectName(_fromUtf8("pushButton_8r"))
        self.verticalLayout_3.addWidget(self.pushButton_8r)
        self.pushButton_9r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9r.setFont(font)
        self.pushButton_9r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9r.setObjectName(_fromUtf8("pushButton_9r"))
        self.verticalLayout_3.addWidget(self.pushButton_9r)
        self.pushButton_10r = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10r.setFont(font)
        self.pushButton_10r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10r.setObjectName(_fromUtf8("pushButton_10r"))
        self.verticalLayout_3.addWidget(self.pushButton_10r)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(70, 120, 271, 251))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEditNaoIP = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoIP.setGeometry(QtCore.QRect(10, 50, 151, 27))
        self.lineEditNaoIP.setObjectName(_fromUtf8("lineEditNaoIP"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 151, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.btnConnectToNao = QtGui.QPushButton(self.groupBox)
        self.btnConnectToNao.setGeometry(QtCore.QRect(10, 150, 251, 91))
        self.btnConnectToNao.setObjectName(_fromUtf8("btnConnectToNao"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 61, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEditNaoPort = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoPort.setGeometry(QtCore.QRect(180, 50, 81, 27))
        self.lineEditNaoPort.setInputMask(_fromUtf8(""))
        self.lineEditNaoPort.setObjectName(_fromUtf8("lineEditNaoPort"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(180, 90, 61, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEditNaoPort_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoPort_2.setGeometry(QtCore.QRect(180, 110, 81, 27))
        self.lineEditNaoPort_2.setInputMask(_fromUtf8(""))
        self.lineEditNaoPort_2.setObjectName(_fromUtf8("lineEditNaoPort_2"))
        self.lineEditNaoIP_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoIP_2.setGeometry(QtCore.QRect(10, 110, 151, 27))
        self.lineEditNaoIP_2.setObjectName(_fromUtf8("lineEditNaoIP_2"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 151, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(850, 120, 321, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 151, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.textEditXML = QtGui.QTextEdit(self.groupBox_2)
        self.textEditXML.setGeometry(QtCore.QRect(20, 50, 211, 71))
        self.textEditXML.setReadOnly(True)
        self.textEditXML.setObjectName(_fromUtf8("textEditXML"))
        self.btnBrowse = QtGui.QPushButton(self.groupBox_2)
        self.btnBrowse.setGeometry(QtCore.QRect(240, 50, 71, 71))
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 120, 391, 451))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btnWakeUp = QtGui.QPushButton(self.groupBox_3)
        self.btnWakeUp.setEnabled(False)
        self.btnWakeUp.setGeometry(QtCore.QRect(10, 50, 361, 91))
        self.btnWakeUp.setObjectName(_fromUtf8("btnWakeUp"))
        self.btnRest = QtGui.QPushButton(self.groupBox_3)
        self.btnRest.setEnabled(False)
        self.btnRest.setGeometry(QtCore.QRect(10, 150, 361, 81))
        self.btnRest.setObjectName(_fromUtf8("btnRest"))
        self.btnFaceTrackingEnable = QtGui.QPushButton(self.groupBox_3)
        self.btnFaceTrackingEnable.setEnabled(False)
        self.btnFaceTrackingEnable.setGeometry(QtCore.QRect(10, 240, 361, 91))
        self.btnFaceTrackingEnable.setObjectName(_fromUtf8("btnFaceTrackingEnable"))
        self.btnFaceTrackingDisable = QtGui.QPushButton(self.groupBox_3)
        self.btnFaceTrackingDisable.setEnabled(False)
        self.btnFaceTrackingDisable.setGeometry(QtCore.QRect(10, 340, 361, 91))
        self.btnFaceTrackingDisable.setObjectName(_fromUtf8("btnFaceTrackingDisable"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(1220, 120, 251, 341))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.textEditSubjectNumber = QtGui.QTextEdit(self.groupBox_7)
        self.textEditSubjectNumber.setGeometry(QtCore.QRect(10, 60, 231, 31))
        self.textEditSubjectNumber.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEditSubjectNumber.setObjectName(_fromUtf8("textEditSubjectNumber"))
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 141, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 141, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.textEditSessionNumber = QtGui.QTextEdit(self.groupBox_7)
        self.textEditSessionNumber.setGeometry(QtCore.QRect(10, 130, 231, 31))
        self.textEditSessionNumber.setObjectName(_fromUtf8("textEditSessionNumber"))
        self.textEditOther = QtGui.QTextEdit(self.groupBox_7)
        self.textEditOther.setGeometry(QtCore.QRect(10, 200, 231, 31))
        self.textEditOther.setObjectName(_fromUtf8("textEditOther"))
        self.label_10 = QtGui.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(10, 180, 67, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.btnSessionInfoConfirm = QtGui.QPushButton(self.groupBox_7)
        self.btnSessionInfoConfirm.setGeometry(QtCore.QRect(10, 260, 231, 61))
        self.btnSessionInfoConfirm.setObjectName(_fromUtf8("btnSessionInfoConfirm"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1920, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "---", None))
        self.btnStartExperiment.setText(_translate("MainWindow", "START", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Welcome, please press START to play the first round...</p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "Player A Bank:", None))
        self.label_5.setText(_translate("MainWindow", "Player B bank:", None))
        self.pushButton_0.setText(_translate("MainWindow", "0", None))
        self.pushButton_1.setText(_translate("MainWindow", "1", None))
        self.pushButton_2.setText(_translate("MainWindow", "2", None))
        self.pushButton_3.setText(_translate("MainWindow", "3", None))
        self.pushButton_4.setText(_translate("MainWindow", "4", None))
        self.pushButton_5.setText(_translate("MainWindow", "5", None))
        self.pushButton_6.setText(_translate("MainWindow", "6", None))
        self.pushButton_7.setText(_translate("MainWindow", "7", None))
        self.pushButton_8.setText(_translate("MainWindow", "8", None))
        self.pushButton_9.setText(_translate("MainWindow", "9", None))
        self.pushButton_10.setText(_translate("MainWindow", "10", None))
        self.pushButton_0r.setText(_translate("MainWindow", "0", None))
        self.pushButton_1r.setText(_translate("MainWindow", "1", None))
        self.pushButton_2r.setText(_translate("MainWindow", "2", None))
        self.pushButton_3r.setText(_translate("MainWindow", "3", None))
        self.pushButton_4r.setText(_translate("MainWindow", "4", None))
        self.pushButton_5r.setText(_translate("MainWindow", "5", None))
        self.pushButton_6r.setText(_translate("MainWindow", "6", None))
        self.pushButton_7r.setText(_translate("MainWindow", "7", None))
        self.pushButton_8r.setText(_translate("MainWindow", "8", None))
        self.pushButton_9r.setText(_translate("MainWindow", "9", None))
        self.pushButton_10r.setText(_translate("MainWindow", "10", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Exp", None))
        self.groupBox.setTitle(_translate("MainWindow", "1- Connection Box", None))
        self.lineEditNaoIP.setInputMask(_translate("MainWindow", "000.000.000.000", None))
        self.lineEditNaoIP.setText(_translate("MainWindow", "192.168.0.100", None))
        self.label.setText(_translate("MainWindow", "NAO IP Address:", None))
        self.btnConnectToNao.setText(_translate("MainWindow", "Connect", None))
        self.label_3.setText(_translate("MainWindow", "Port:", None))
        self.lineEditNaoPort.setText(_translate("MainWindow", "9559", None))
        self.label_8.setText(_translate("MainWindow", "Por-2t:", None))
        self.lineEditNaoPort_2.setText(_translate("MainWindow", "9559", None))
        self.lineEditNaoIP_2.setInputMask(_translate("MainWindow", "000.000.000.000", None))
        self.lineEditNaoIP_2.setText(_translate("MainWindow", "192.168.0.101", None))
        self.label_7.setText(_translate("MainWindow", "NAO-2 IP Address:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "3- XML file", None))
        self.label_2.setText(_translate("MainWindow", "XML path:", None))
        self.btnBrowse.setText(_translate("MainWindow", "...", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "2- Robt Control", None))
        self.btnWakeUp.setText(_translate("MainWindow", "Init Position", None))
        self.btnRest.setText(_translate("MainWindow", "Rest", None))
        self.btnFaceTrackingEnable.setText(_translate("MainWindow", "Enable Face Tracking", None))
        self.btnFaceTrackingDisable.setText(_translate("MainWindow", "Disable Face Tracking", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "4- Session info", None))
        self.textEditSubjectNumber.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "Subject Number:", None))
        self.label_9.setText(_translate("MainWindow", "Session Number:", None))
        self.textEditSessionNumber.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.textEditOther.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "Other:", None))
        self.btnSessionInfoConfirm.setText(_translate("MainWindow", "Confirm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Admin", None))

