# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../include/mainwindow.ui'
#
# Created: Mon Dec  4 11:21:14 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1920, 1080)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(240, 520, 1411, 131))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(660, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_8.setGeometry(QtCore.QRect(1030, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_1 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_1.setGeometry(QtCore.QRect(160, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_9.setGeometry(QtCore.QRect(1160, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_10.setGeometry(QtCore.QRect(1280, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_7.setGeometry(QtCore.QRect(910, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_6.setGeometry(QtCore.QRect(780, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_0 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_0.setGeometry(QtCore.QRect(40, 20, 99, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_0.setObjectName(_fromUtf8("pushButton_0"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(450, 200, 1001, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        self.textEdit.setFont(font)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.lcdNumberTotal = QtGui.QLCDNumber(self.tab)
        self.lcdNumberTotal.setGeometry(QtCore.QRect(450, 50, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberTotal.setFont(font)
        self.lcdNumberTotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumberTotal.setAutoFillBackground(False)
        self.lcdNumberTotal.setSmallDecimalPoint(False)
        self.lcdNumberTotal.setProperty("value", 0.0)
        self.lcdNumberTotal.setProperty("intValue", 0)
        self.lcdNumberTotal.setObjectName(_fromUtf8("lcdNumberTotal"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(450, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(1000, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lcdNumberTotal1 = QtGui.QLCDNumber(self.tab)
        self.lcdNumberTotal1.setGeometry(QtCore.QRect(1000, 50, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberTotal1.setFont(font)
        self.lcdNumberTotal1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumberTotal1.setAutoFillBackground(False)
        self.lcdNumberTotal1.setProperty("intValue", 0)
        self.lcdNumberTotal1.setObjectName(_fromUtf8("lcdNumberTotal1"))
        self.btnStartExperiment = QtGui.QPushButton(self.tab)
        self.btnStartExperiment.setGeometry(QtCore.QRect(660, 790, 570, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartExperiment.setFont(font)
        self.btnStartExperiment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStartExperiment.setObjectName(_fromUtf8("btnStartExperiment"))
        self.lcdNumberTotal2 = QtGui.QLCDNumber(self.tab)
        self.lcdNumberTotal2.setGeometry(QtCore.QRect(1160, 50, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberTotal2.setFont(font)
        self.lcdNumberTotal2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumberTotal2.setAutoFillBackground(False)
        self.lcdNumberTotal2.setProperty("value", 0.0)
        self.lcdNumberTotal2.setProperty("intValue", 0)
        self.lcdNumberTotal2.setObjectName(_fromUtf8("lcdNumberTotal2"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(1160, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lcdNumberTotal3 = QtGui.QLCDNumber(self.tab)
        self.lcdNumberTotal3.setGeometry(QtCore.QRect(1320, 50, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberTotal3.setFont(font)
        self.lcdNumberTotal3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumberTotal3.setAutoFillBackground(False)
        self.lcdNumberTotal3.setProperty("value", 0.0)
        self.lcdNumberTotal3.setProperty("intValue", 0)
        self.lcdNumberTotal3.setObjectName(_fromUtf8("lcdNumberTotal3"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(1320, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(70, 120, 271, 331))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEditNaoIP = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoIP.setGeometry(QtCore.QRect(10, 50, 151, 27))
        self.lineEditNaoIP.setObjectName(_fromUtf8("lineEditNaoIP"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 151, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.btnConnectToNao = QtGui.QPushButton(self.groupBox)
        self.btnConnectToNao.setGeometry(QtCore.QRect(10, 220, 251, 91))
        self.btnConnectToNao.setObjectName(_fromUtf8("btnConnectToNao"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 61, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEditNaoPort = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoPort.setGeometry(QtCore.QRect(180, 50, 81, 27))
        self.lineEditNaoPort.setInputMask(_fromUtf8(""))
        self.lineEditNaoPort.setObjectName(_fromUtf8("lineEditNaoPort"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(180, 90, 61, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEditNaoPort_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoPort_2.setGeometry(QtCore.QRect(180, 110, 81, 27))
        self.lineEditNaoPort_2.setInputMask(_fromUtf8(""))
        self.lineEditNaoPort_2.setObjectName(_fromUtf8("lineEditNaoPort_2"))
        self.lineEditNaoIP_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoIP_2.setGeometry(QtCore.QRect(10, 110, 151, 27))
        self.lineEditNaoIP_2.setObjectName(_fromUtf8("lineEditNaoIP_2"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 151, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEditNaoIP_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoIP_3.setGeometry(QtCore.QRect(10, 170, 151, 27))
        self.lineEditNaoIP_3.setObjectName(_fromUtf8("lineEditNaoIP_3"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 151, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEditNaoPort_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEditNaoPort_3.setGeometry(QtCore.QRect(180, 170, 81, 27))
        self.lineEditNaoPort_3.setInputMask(_fromUtf8(""))
        self.lineEditNaoPort_3.setObjectName(_fromUtf8("lineEditNaoPort_3"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(180, 150, 61, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(850, 120, 321, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 151, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.textEditXML = QtGui.QTextEdit(self.groupBox_2)
        self.textEditXML.setGeometry(QtCore.QRect(20, 50, 211, 71))
        self.textEditXML.setReadOnly(True)
        self.textEditXML.setObjectName(_fromUtf8("textEditXML"))
        self.btnBrowse = QtGui.QPushButton(self.groupBox_2)
        self.btnBrowse.setGeometry(QtCore.QRect(240, 50, 71, 71))
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 120, 391, 451))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btnWakeUp = QtGui.QPushButton(self.groupBox_3)
        self.btnWakeUp.setEnabled(False)
        self.btnWakeUp.setGeometry(QtCore.QRect(10, 50, 361, 91))
        self.btnWakeUp.setObjectName(_fromUtf8("btnWakeUp"))
        self.btnRest = QtGui.QPushButton(self.groupBox_3)
        self.btnRest.setEnabled(False)
        self.btnRest.setGeometry(QtCore.QRect(10, 150, 361, 81))
        self.btnRest.setObjectName(_fromUtf8("btnRest"))
        self.btnFaceTrackingEnable = QtGui.QPushButton(self.groupBox_3)
        self.btnFaceTrackingEnable.setEnabled(False)
        self.btnFaceTrackingEnable.setGeometry(QtCore.QRect(10, 240, 361, 91))
        self.btnFaceTrackingEnable.setObjectName(_fromUtf8("btnFaceTrackingEnable"))
        self.btnFaceTrackingDisable = QtGui.QPushButton(self.groupBox_3)
        self.btnFaceTrackingDisable.setEnabled(False)
        self.btnFaceTrackingDisable.setGeometry(QtCore.QRect(10, 340, 361, 91))
        self.btnFaceTrackingDisable.setObjectName(_fromUtf8("btnFaceTrackingDisable"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(1220, 120, 251, 341))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.textEditSubjectNumber = QtGui.QTextEdit(self.groupBox_7)
        self.textEditSubjectNumber.setGeometry(QtCore.QRect(10, 60, 231, 31))
        self.textEditSubjectNumber.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEditSubjectNumber.setObjectName(_fromUtf8("textEditSubjectNumber"))
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 141, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 141, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.textEditSessionNumber = QtGui.QTextEdit(self.groupBox_7)
        self.textEditSessionNumber.setGeometry(QtCore.QRect(10, 130, 231, 31))
        self.textEditSessionNumber.setObjectName(_fromUtf8("textEditSessionNumber"))
        self.textEditOther = QtGui.QTextEdit(self.groupBox_7)
        self.textEditOther.setGeometry(QtCore.QRect(10, 200, 231, 31))
        self.textEditOther.setObjectName(_fromUtf8("textEditOther"))
        self.label_10 = QtGui.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(10, 180, 67, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.btnSessionInfoConfirm = QtGui.QPushButton(self.groupBox_7)
        self.btnSessionInfoConfirm.setGeometry(QtCore.QRect(10, 260, 231, 61))
        self.btnSessionInfoConfirm.setObjectName(_fromUtf8("btnSessionInfoConfirm"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1920, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "---", None))
        self.pushButton_5.setText(_translate("MainWindow", "5", None))
        self.pushButton_2.setText(_translate("MainWindow", "2", None))
        self.pushButton_3.setText(_translate("MainWindow", "3", None))
        self.pushButton_8.setText(_translate("MainWindow", "8", None))
        self.pushButton_1.setText(_translate("MainWindow", "1", None))
        self.pushButton_9.setText(_translate("MainWindow", "9", None))
        self.pushButton_10.setText(_translate("MainWindow", "10", None))
        self.pushButton_7.setText(_translate("MainWindow", "7", None))
        self.pushButton_4.setText(_translate("MainWindow", "4", None))
        self.pushButton_6.setText(_translate("MainWindow", "6", None))
        self.pushButton_0.setText(_translate("MainWindow", "0", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Welcome, please press START to play the first round...</p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "Your Bank:", None))
        self.label_5.setText(_translate("MainWindow", "Pepper bank:", None))
        self.btnStartExperiment.setText(_translate("MainWindow", "START", None))
        self.label_13.setText(_translate("MainWindow", "Tommy bank:", None))
        self.label_14.setText(_translate("MainWindow", "Jones bank:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Exp", None))
        self.groupBox.setTitle(_translate("MainWindow", "1- Connection Box", None))
        self.lineEditNaoIP.setInputMask(_translate("MainWindow", "000.000.000.000", None))
        self.lineEditNaoIP.setText(_translate("MainWindow", "192.168.0.101", None))
        self.label.setText(_translate("MainWindow", "Leader-1 IP Address:", None))
        self.btnConnectToNao.setText(_translate("MainWindow", "Connect", None))
        self.label_3.setText(_translate("MainWindow", "Port:", None))
        self.lineEditNaoPort.setText(_translate("MainWindow", "9559", None))
        self.label_8.setText(_translate("MainWindow", "Port-2:", None))
        self.lineEditNaoPort_2.setText(_translate("MainWindow", "9559", None))
        self.lineEditNaoIP_2.setInputMask(_translate("MainWindow", "000.000.000.000", None))
        self.lineEditNaoIP_2.setText(_translate("MainWindow", "192.168.0.102", None))
        self.label_7.setText(_translate("MainWindow", "Robot-2 IP Address:", None))
        self.lineEditNaoIP_3.setInputMask(_translate("MainWindow", "000.000.000.000", None))
        self.lineEditNaoIP_3.setText(_translate("MainWindow", "192.168.0.100", None))
        self.label_11.setText(_translate("MainWindow", "Robot-3 IP Address:", None))
        self.lineEditNaoPort_3.setText(_translate("MainWindow", "9559", None))
        self.label_12.setText(_translate("MainWindow", "Port-3:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "3- XML file", None))
        self.label_2.setText(_translate("MainWindow", "XML path:", None))
        self.btnBrowse.setText(_translate("MainWindow", "...", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "2- Robt Control", None))
        self.btnWakeUp.setText(_translate("MainWindow", "Init Position", None))
        self.btnRest.setText(_translate("MainWindow", "Rest", None))
        self.btnFaceTrackingEnable.setText(_translate("MainWindow", "Enable Face Tracking", None))
        self.btnFaceTrackingDisable.setText(_translate("MainWindow", "Disable Face Tracking", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "4- Session info", None))
        self.textEditSubjectNumber.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "Subject Number:", None))
        self.label_9.setText(_translate("MainWindow", "Session Number:", None))
        self.textEditSessionNumber.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.textEditOther.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "Other:", None))
        self.btnSessionInfoConfirm.setText(_translate("MainWindow", "Confirm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Admin", None))

